org: therealgaryj
app: hiringtests
service: hiringtests

frameworkVersion: ">=2.0.0"

#resources:
#  NotesBucket:
#    Type: S3::Bucket
resources:
  Resources:
    LambdaCloudwatchInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: arn:aws:lambda:${self:provider.region}:${self:custom.awsAccountId}:function:logzio-cloudwatch-log-shipper
        Principal: logs.${self:provider.region}.amazonaws.com
        Action: "lambda:InvokeFunction"
        SourceArn: arn:aws:logs:${self:provider.region}:${self:custom.awsAccountId}:log-group:*:*
provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  primes-api:
    handler: "bin/primes-api"
    kmsKeyArn: arn:aws:kms:${self:provider.region}:${self:custom.awsAccountId}:key/${self:custom.kmsKeyArn}
    environment:
      LOG_LEVEL: "DEBUG"
    events:
      - http:
          path: "primes/{prime}"
          method: "any"
plugins:
  - serverless-domain-manager
  - serverless-plugin-log-subscription
custom:
  awsAccountId: "693619507695"
  kmsKeyArn: "eb6d3ec2-bbce-4d71-8586-2172b49a1bbf"
  customDomain:
    domainName: "hiringtests.co.uk"
    stage: ${opt:stage, self:provider.stage}
    basePath: ""
    certificateName: "hiringtests.co.uk"
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
  logSubscription:
    enabled: true
    destinationArn: arn:aws:lambda:${self:provider.region}:${self:custom.awsAccountId}:function:logzio-cloudwatch-log-shipper